export default {
    title: '年度报告',
    date: '2021年',
    name: '群聊名称',
    memberCount: 0,
    totalMsg: 0,
    totalImg: 0,
    totalWords: 0,
    bookCount: 0,
    maxImg: 0,
    maxImgName: '',
    maxRepeat: 0,
    maxRepeatName: 0,
    maxWordName: '',
    maxWords: '',
    maxActive: '',
    maxActiveName: '',
    activeDate: '月份',
    activeDateData: 0,
    activePeriod: '时间',
    activePeriodData: 0,
    topKeywordCount: 0,
    topKeyword: '',
    longestContent: '',
    longestContentName: '',
    topRepeat: '',
    topRepeatCount: ''
}